# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-armsbc-dca.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3568-armsbc-dca.dtb
#dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3588-armsbc-dca.dtb
#dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3588-armsbc-rwa.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3566-armsbc-dca.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3568-armsbc-nano.dtb
#dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3588-armsbc-edge.dtb
